export type TileSide = 'upright' | 'side_left' | 'side_right';

const TILE_ASSETS: Record<string, any> = {
  'w1': require('./assets/tiles/hd/w1.png'),
  'w2': require('./assets/tiles/hd/w2.png'),
  'w3': require('./assets/tiles/hd/w3.png'),
  'w4': require('./assets/tiles/hd/w4.png'),
  'w5': require('./assets/tiles/hd/w5.png'),
  'w6': require('./assets/tiles/hd/w6.png'),
  'w7': require('./assets/tiles/hd/w7.png'),
  'w8': require('./assets/tiles/hd/w8.png'),
  'w9': require('./assets/tiles/hd/w9.png'),
  't1': require('./assets/tiles/hd/t1.png'),
  't2': require('./assets/tiles/hd/t2.png'),
  't3': require('./assets/tiles/hd/t3.png'),
  't4': require('./assets/tiles/hd/t4.png'),
  't5': require('./assets/tiles/hd/t5.png'),
  't6': require('./assets/tiles/hd/t6.png'),
  't7': require('./assets/tiles/hd/t7.png'),
  't8': require('./assets/tiles/hd/t8.png'),
  't9': require('./assets/tiles/hd/t9.png'),
  'b1': require('./assets/tiles/hd/b1.png'),
  'b2': require('./assets/tiles/hd/b2.png'),
  'b3': require('./assets/tiles/hd/b3.png'),
  'b4': require('./assets/tiles/hd/b4.png'),
  'b5': require('./assets/tiles/hd/b5.png'),
  'b6': require('./assets/tiles/hd/b6.png'),
  'b7': require('./assets/tiles/hd/b7.png'),
  'b8': require('./assets/tiles/hd/b8.png'),
  'b9': require('./assets/tiles/hd/b9.png'),
  'w1_side_left': require('./assets/tiles/hd/w1_side_left.png'),
  'w2_side_left': require('./assets/tiles/hd/w2_side_left.png'),
  'w3_side_left': require('./assets/tiles/hd/w3_side_left.png'),
  'w4_side_left': require('./assets/tiles/hd/w4_side_left.png'),
  'w5_side_left': require('./assets/tiles/hd/w5_side_left.png'),
  'w6_side_left': require('./assets/tiles/hd/w6_side_left.png'),
  'w7_side_left': require('./assets/tiles/hd/w7_side_left.png'),
  'w8_side_left': require('./assets/tiles/hd/w8_side_left.png'),
  'w9_side_left': require('./assets/tiles/hd/w9_side_left.png'),
  't1_side_left': require('./assets/tiles/hd/t1_side_left.png'),
  't2_side_left': require('./assets/tiles/hd/t2_side_left.png'),
  't3_side_left': require('./assets/tiles/hd/t3_side_left.png'),
  't4_side_left': require('./assets/tiles/hd/t4_side_left.png'),
  't5_side_left': require('./assets/tiles/hd/t5_side_left.png'),
  't6_side_left': require('./assets/tiles/hd/t6_side_left.png'),
  't7_side_left': require('./assets/tiles/hd/t7_side_left.png'),
  't8_side_left': require('./assets/tiles/hd/t8_side_left.png'),
  't9_side_left': require('./assets/tiles/hd/t9_side_left.png'),
  'b1_side_left': require('./assets/tiles/hd/b1_side_left.png'),
  'b2_side_left': require('./assets/tiles/hd/b2_side_left.png'),
  'b3_side_left': require('./assets/tiles/hd/b3_side_left.png'),
  'b4_side_left': require('./assets/tiles/hd/b4_side_left.png'),
  'b5_side_left': require('./assets/tiles/hd/b5_side_left.png'),
  'b6_side_left': require('./assets/tiles/hd/b6_side_left.png'),
  'b7_side_left': require('./assets/tiles/hd/b7_side_left.png'),
  'b8_side_left': require('./assets/tiles/hd/b8_side_left.png'),
  'b9_side_left': require('./assets/tiles/hd/b9_side_left.png'),
  'w1_side_right': require('./assets/tiles/hd/w1_side_right.png'),
  'w2_side_right': require('./assets/tiles/hd/w2_side_right.png'),
  'w3_side_right': require('./assets/tiles/hd/w3_side_right.png'),
  'w4_side_right': require('./assets/tiles/hd/w4_side_right.png'),
  'w5_side_right': require('./assets/tiles/hd/w5_side_right.png'),
  'w6_side_right': require('./assets/tiles/hd/w6_side_right.png'),
  'w7_side_right': require('./assets/tiles/hd/w7_side_right.png'),
  'w8_side_right': require('./assets/tiles/hd/w8_side_right.png'),
  'w9_side_right': require('./assets/tiles/hd/w9_side_right.png'),
  't1_side_right': require('./assets/tiles/hd/t1_side_right.png'),
  't2_side_right': require('./assets/tiles/hd/t2_side_right.png'),
  't3_side_right': require('./assets/tiles/hd/t3_side_right.png'),
  't4_side_right': require('./assets/tiles/hd/t4_side_right.png'),
  't5_side_right': require('./assets/tiles/hd/t5_side_right.png'),
  't6_side_right': require('./assets/tiles/hd/t6_side_right.png'),
  't7_side_right': require('./assets/tiles/hd/t7_side_right.png'),
  't8_side_right': require('./assets/tiles/hd/t8_side_right.png'),
  't9_side_right': require('./assets/tiles/hd/t9_side_right.png'),
  'b1_side_right': require('./assets/tiles/hd/b1_side_right.png'),
  'b2_side_right': require('./assets/tiles/hd/b2_side_right.png'),
  'b3_side_right': require('./assets/tiles/hd/b3_side_right.png'),
  'b4_side_right': require('./assets/tiles/hd/b4_side_right.png'),
  'b5_side_right': require('./assets/tiles/hd/b5_side_right.png'),
  'b6_side_right': require('./assets/tiles/hd/b6_side_right.png'),
  'b7_side_right': require('./assets/tiles/hd/b7_side_right.png'),
  'b8_side_right': require('./assets/tiles/hd/b8_side_right.png'),
  'b9_side_right': require('./assets/tiles/hd/b9_side_right.png'),
};

export function getTileAsset(code: string, side: TileSide = "upright"): any | null {
  const pure = code.includes("@") ? code.split("@")[0] : code;
  const key = side === "upright" ? pure : `${pure}_${side}`;
  return TILE_ASSETS[key] || null;
}
