export type TileSide = 'upright' | 'side_left' | 'side_right';
export type TileStyle = 'hd0' | 'hd1';

let currentTileStyle: TileStyle = 'hd0';

const TILE_ASSETS_BY_STYLE: Record<TileStyle, Record<string, any>> = {
  hd0: {
    'back': require('../MahjongMacHost/assets/tiles/hd/hd0/back.png'),
    'back_top': require('../MahjongMacHost/assets/tiles/hd/hd0/back.png'),
    'back_side_left': require('../MahjongMacHost/assets/tiles/hd/hd0/back_side_left.png'),
    'back_side_right': require('../MahjongMacHost/assets/tiles/hd/hd0/back_side_right.png'),
    'fold': require('../MahjongMacHost/assets/tiles/hd/hd0/fold.png'),
    'fold_side_left': require('../MahjongMacHost/assets/tiles/hd/hd0/fold_side_left.png'),
    'fold_side_right': require('../MahjongMacHost/assets/tiles/hd/hd0/fold_side_right.png'),
    '+': require('../MahjongMacHost/assets/tiles/hd/hd0/fold.png'),
    '+_side_left': require('../MahjongMacHost/assets/tiles/hd/hd0/fold_side_left.png'),
    '+_side_right': require('../MahjongMacHost/assets/tiles/hd/hd0/fold_side_right.png'),
    'w1': require('../MahjongMacHost/assets/tiles/hd/hd0/w1.png'),
    'w1_side_left': require('../MahjongMacHost/assets/tiles/hd/hd0/w1_side_left.png'),
    'w1_side_right': require('../MahjongMacHost/assets/tiles/hd/hd0/w1_side_right.png'),
    'w2': require('../MahjongMacHost/assets/tiles/hd/hd0/w2.png'),
    'w2_side_left': require('../MahjongMacHost/assets/tiles/hd/hd0/w2_side_left.png'),
    'w2_side_right': require('../MahjongMacHost/assets/tiles/hd/hd0/w2_side_right.png'),
    'w3': require('../MahjongMacHost/assets/tiles/hd/hd0/w3.png'),
    'w3_side_left': require('../MahjongMacHost/assets/tiles/hd/hd0/w3_side_left.png'),
    'w3_side_right': require('../MahjongMacHost/assets/tiles/hd/hd0/w3_side_right.png'),
    'w4': require('../MahjongMacHost/assets/tiles/hd/hd0/w4.png'),
    'w4_side_left': require('../MahjongMacHost/assets/tiles/hd/hd0/w4_side_left.png'),
    'w4_side_right': require('../MahjongMacHost/assets/tiles/hd/hd0/w4_side_right.png'),
    'w5': require('../MahjongMacHost/assets/tiles/hd/hd0/w5.png'),
    'w5_side_left': require('../MahjongMacHost/assets/tiles/hd/hd0/w5_side_left.png'),
    'w5_side_right': require('../MahjongMacHost/assets/tiles/hd/hd0/w5_side_right.png'),
    'w6': require('../MahjongMacHost/assets/tiles/hd/hd0/w6.png'),
    'w6_side_left': require('../MahjongMacHost/assets/tiles/hd/hd0/w6_side_left.png'),
    'w6_side_right': require('../MahjongMacHost/assets/tiles/hd/hd0/w6_side_right.png'),
    'w7': require('../MahjongMacHost/assets/tiles/hd/hd0/w7.png'),
    'w7_side_left': require('../MahjongMacHost/assets/tiles/hd/hd0/w7_side_left.png'),
    'w7_side_right': require('../MahjongMacHost/assets/tiles/hd/hd0/w7_side_right.png'),
    'w8': require('../MahjongMacHost/assets/tiles/hd/hd0/w8.png'),
    'w8_side_left': require('../MahjongMacHost/assets/tiles/hd/hd0/w8_side_left.png'),
    'w8_side_right': require('../MahjongMacHost/assets/tiles/hd/hd0/w8_side_right.png'),
    'w9': require('../MahjongMacHost/assets/tiles/hd/hd0/w9.png'),
    'w9_side_left': require('../MahjongMacHost/assets/tiles/hd/hd0/w9_side_left.png'),
    'w9_side_right': require('../MahjongMacHost/assets/tiles/hd/hd0/w9_side_right.png'),
    't1': require('../MahjongMacHost/assets/tiles/hd/hd0/t1.png'),
    't1_side_left': require('../MahjongMacHost/assets/tiles/hd/hd0/t1_side_left.png'),
    't1_side_right': require('../MahjongMacHost/assets/tiles/hd/hd0/t1_side_right.png'),
    't2': require('../MahjongMacHost/assets/tiles/hd/hd0/t2.png'),
    't2_side_left': require('../MahjongMacHost/assets/tiles/hd/hd0/t2_side_left.png'),
    't2_side_right': require('../MahjongMacHost/assets/tiles/hd/hd0/t2_side_right.png'),
    't3': require('../MahjongMacHost/assets/tiles/hd/hd0/t3.png'),
    't3_side_left': require('../MahjongMacHost/assets/tiles/hd/hd0/t3_side_left.png'),
    't3_side_right': require('../MahjongMacHost/assets/tiles/hd/hd0/t3_side_right.png'),
    't4': require('../MahjongMacHost/assets/tiles/hd/hd0/t4.png'),
    't4_side_left': require('../MahjongMacHost/assets/tiles/hd/hd0/t4_side_left.png'),
    't4_side_right': require('../MahjongMacHost/assets/tiles/hd/hd0/t4_side_right.png'),
    't5': require('../MahjongMacHost/assets/tiles/hd/hd0/t5.png'),
    't5_side_left': require('../MahjongMacHost/assets/tiles/hd/hd0/t5_side_left.png'),
    't5_side_right': require('../MahjongMacHost/assets/tiles/hd/hd0/t5_side_right.png'),
    't6': require('../MahjongMacHost/assets/tiles/hd/hd0/t6.png'),
    't6_side_left': require('../MahjongMacHost/assets/tiles/hd/hd0/t6_side_left.png'),
    't6_side_right': require('../MahjongMacHost/assets/tiles/hd/hd0/t6_side_right.png'),
    't7': require('../MahjongMacHost/assets/tiles/hd/hd0/t7.png'),
    't7_side_left': require('../MahjongMacHost/assets/tiles/hd/hd0/t7_side_left.png'),
    't7_side_right': require('../MahjongMacHost/assets/tiles/hd/hd0/t7_side_right.png'),
    't8': require('../MahjongMacHost/assets/tiles/hd/hd0/t8.png'),
    't8_side_left': require('../MahjongMacHost/assets/tiles/hd/hd0/t8_side_left.png'),
    't8_side_right': require('../MahjongMacHost/assets/tiles/hd/hd0/t8_side_right.png'),
    't9': require('../MahjongMacHost/assets/tiles/hd/hd0/t9.png'),
    't9_side_left': require('../MahjongMacHost/assets/tiles/hd/hd0/t9_side_left.png'),
    't9_side_right': require('../MahjongMacHost/assets/tiles/hd/hd0/t9_side_right.png'),
    'b1': require('../MahjongMacHost/assets/tiles/hd/hd0/b1.png'),
    'b1_side_left': require('../MahjongMacHost/assets/tiles/hd/hd0/b1_side_left.png'),
    'b1_side_right': require('../MahjongMacHost/assets/tiles/hd/hd0/b1_side_right.png'),
    'b2': require('../MahjongMacHost/assets/tiles/hd/hd0/b2.png'),
    'b2_side_left': require('../MahjongMacHost/assets/tiles/hd/hd0/b2_side_left.png'),
    'b2_side_right': require('../MahjongMacHost/assets/tiles/hd/hd0/b2_side_right.png'),
    'b3': require('../MahjongMacHost/assets/tiles/hd/hd0/b3.png'),
    'b3_side_left': require('../MahjongMacHost/assets/tiles/hd/hd0/b3_side_left.png'),
    'b3_side_right': require('../MahjongMacHost/assets/tiles/hd/hd0/b3_side_right.png'),
    'b4': require('../MahjongMacHost/assets/tiles/hd/hd0/b4.png'),
    'b4_side_left': require('../MahjongMacHost/assets/tiles/hd/hd0/b4_side_left.png'),
    'b4_side_right': require('../MahjongMacHost/assets/tiles/hd/hd0/b4_side_right.png'),
    'b5': require('../MahjongMacHost/assets/tiles/hd/hd0/b5.png'),
    'b5_side_left': require('../MahjongMacHost/assets/tiles/hd/hd0/b5_side_left.png'),
    'b5_side_right': require('../MahjongMacHost/assets/tiles/hd/hd0/b5_side_right.png'),
    'b6': require('../MahjongMacHost/assets/tiles/hd/hd0/b6.png'),
    'b6_side_left': require('../MahjongMacHost/assets/tiles/hd/hd0/b6_side_left.png'),
    'b6_side_right': require('../MahjongMacHost/assets/tiles/hd/hd0/b6_side_right.png'),
    'b7': require('../MahjongMacHost/assets/tiles/hd/hd0/b7.png'),
    'b7_side_left': require('../MahjongMacHost/assets/tiles/hd/hd0/b7_side_left.png'),
    'b7_side_right': require('../MahjongMacHost/assets/tiles/hd/hd0/b7_side_right.png'),
    'b8': require('../MahjongMacHost/assets/tiles/hd/hd0/b8.png'),
    'b8_side_left': require('../MahjongMacHost/assets/tiles/hd/hd0/b8_side_left.png'),
    'b8_side_right': require('../MahjongMacHost/assets/tiles/hd/hd0/b8_side_right.png'),
    'b9': require('../MahjongMacHost/assets/tiles/hd/hd0/b9.png'),
    'b9_side_left': require('../MahjongMacHost/assets/tiles/hd/hd0/b9_side_left.png'),
    'b9_side_right': require('../MahjongMacHost/assets/tiles/hd/hd0/b9_side_right.png'),
  },
  hd1: {
    'back': require('../MahjongMacHost/assets/tiles/hd/hd1/back.png'),
    'back_top': require('../MahjongMacHost/assets/tiles/hd/hd1/back.png'),
    'back_side_left': require('../MahjongMacHost/assets/tiles/hd/hd1/back_side_left.png'),
    'back_side_right': require('../MahjongMacHost/assets/tiles/hd/hd1/back_side_right.png'),
    'fold': require('../MahjongMacHost/assets/tiles/hd/hd1/fold.png'),
    'fold_side_left': require('../MahjongMacHost/assets/tiles/hd/hd1/fold_side_left.png'),
    'fold_side_right': require('../MahjongMacHost/assets/tiles/hd/hd1/fold_side_right.png'),
    '+': require('../MahjongMacHost/assets/tiles/hd/hd1/fold.png'),
    '+_side_left': require('../MahjongMacHost/assets/tiles/hd/hd1/fold_side_left.png'),
    '+_side_right': require('../MahjongMacHost/assets/tiles/hd/hd1/fold_side_right.png'),
    'w1': require('../MahjongMacHost/assets/tiles/hd/hd1/w1.png'),
    'w1_side_left': require('../MahjongMacHost/assets/tiles/hd/hd1/w1_side_left.png'),
    'w1_side_right': require('../MahjongMacHost/assets/tiles/hd/hd1/w1_side_right.png'),
    'w2': require('../MahjongMacHost/assets/tiles/hd/hd1/w2.png'),
    'w2_side_left': require('../MahjongMacHost/assets/tiles/hd/hd1/w2_side_left.png'),
    'w2_side_right': require('../MahjongMacHost/assets/tiles/hd/hd1/w2_side_right.png'),
    'w3': require('../MahjongMacHost/assets/tiles/hd/hd1/w3.png'),
    'w3_side_left': require('../MahjongMacHost/assets/tiles/hd/hd1/w3_side_left.png'),
    'w3_side_right': require('../MahjongMacHost/assets/tiles/hd/hd1/w3_side_right.png'),
    'w4': require('../MahjongMacHost/assets/tiles/hd/hd1/w4.png'),
    'w4_side_left': require('../MahjongMacHost/assets/tiles/hd/hd1/w4_side_left.png'),
    'w4_side_right': require('../MahjongMacHost/assets/tiles/hd/hd1/w4_side_right.png'),
    'w5': require('../MahjongMacHost/assets/tiles/hd/hd1/w5.png'),
    'w5_side_left': require('../MahjongMacHost/assets/tiles/hd/hd1/w5_side_left.png'),
    'w5_side_right': require('../MahjongMacHost/assets/tiles/hd/hd1/w5_side_right.png'),
    'w6': require('../MahjongMacHost/assets/tiles/hd/hd1/w6.png'),
    'w6_side_left': require('../MahjongMacHost/assets/tiles/hd/hd1/w6_side_left.png'),
    'w6_side_right': require('../MahjongMacHost/assets/tiles/hd/hd1/w6_side_right.png'),
    'w7': require('../MahjongMacHost/assets/tiles/hd/hd1/w7.png'),
    'w7_side_left': require('../MahjongMacHost/assets/tiles/hd/hd1/w7_side_left.png'),
    'w7_side_right': require('../MahjongMacHost/assets/tiles/hd/hd1/w7_side_right.png'),
    'w8': require('../MahjongMacHost/assets/tiles/hd/hd1/w8.png'),
    'w8_side_left': require('../MahjongMacHost/assets/tiles/hd/hd1/w8_side_left.png'),
    'w8_side_right': require('../MahjongMacHost/assets/tiles/hd/hd1/w8_side_right.png'),
    'w9': require('../MahjongMacHost/assets/tiles/hd/hd1/w9.png'),
    'w9_side_left': require('../MahjongMacHost/assets/tiles/hd/hd1/w9_side_left.png'),
    'w9_side_right': require('../MahjongMacHost/assets/tiles/hd/hd1/w9_side_right.png'),
    't1': require('../MahjongMacHost/assets/tiles/hd/hd1/t1.png'),
    't1_side_left': require('../MahjongMacHost/assets/tiles/hd/hd1/t1_side_left.png'),
    't1_side_right': require('../MahjongMacHost/assets/tiles/hd/hd1/t1_side_right.png'),
    't2': require('../MahjongMacHost/assets/tiles/hd/hd1/t2.png'),
    't2_side_left': require('../MahjongMacHost/assets/tiles/hd/hd1/t2_side_left.png'),
    't2_side_right': require('../MahjongMacHost/assets/tiles/hd/hd1/t2_side_right.png'),
    't3': require('../MahjongMacHost/assets/tiles/hd/hd1/t3.png'),
    't3_side_left': require('../MahjongMacHost/assets/tiles/hd/hd1/t3_side_left.png'),
    't3_side_right': require('../MahjongMacHost/assets/tiles/hd/hd1/t3_side_right.png'),
    't4': require('../MahjongMacHost/assets/tiles/hd/hd1/t4.png'),
    't4_side_left': require('../MahjongMacHost/assets/tiles/hd/hd1/t4_side_left.png'),
    't4_side_right': require('../MahjongMacHost/assets/tiles/hd/hd1/t4_side_right.png'),
    't5': require('../MahjongMacHost/assets/tiles/hd/hd1/t5.png'),
    't5_side_left': require('../MahjongMacHost/assets/tiles/hd/hd1/t5_side_left.png'),
    't5_side_right': require('../MahjongMacHost/assets/tiles/hd/hd1/t5_side_right.png'),
    't6': require('../MahjongMacHost/assets/tiles/hd/hd1/t6.png'),
    't6_side_left': require('../MahjongMacHost/assets/tiles/hd/hd1/t6_side_left.png'),
    't6_side_right': require('../MahjongMacHost/assets/tiles/hd/hd1/t6_side_right.png'),
    't7': require('../MahjongMacHost/assets/tiles/hd/hd1/t7.png'),
    't7_side_left': require('../MahjongMacHost/assets/tiles/hd/hd1/t7_side_left.png'),
    't7_side_right': require('../MahjongMacHost/assets/tiles/hd/hd1/t7_side_right.png'),
    't8': require('../MahjongMacHost/assets/tiles/hd/hd1/t8.png'),
    't8_side_left': require('../MahjongMacHost/assets/tiles/hd/hd1/t8_side_left.png'),
    't8_side_right': require('../MahjongMacHost/assets/tiles/hd/hd1/t8_side_right.png'),
    't9': require('../MahjongMacHost/assets/tiles/hd/hd1/t9.png'),
    't9_side_left': require('../MahjongMacHost/assets/tiles/hd/hd1/t9_side_left.png'),
    't9_side_right': require('../MahjongMacHost/assets/tiles/hd/hd1/t9_side_right.png'),
    'b1': require('../MahjongMacHost/assets/tiles/hd/hd1/b1.png'),
    'b1_side_left': require('../MahjongMacHost/assets/tiles/hd/hd1/b1_side_left.png'),
    'b1_side_right': require('../MahjongMacHost/assets/tiles/hd/hd1/b1_side_right.png'),
    'b2': require('../MahjongMacHost/assets/tiles/hd/hd1/b2.png'),
    'b2_side_left': require('../MahjongMacHost/assets/tiles/hd/hd1/b2_side_left.png'),
    'b2_side_right': require('../MahjongMacHost/assets/tiles/hd/hd1/b2_side_right.png'),
    'b3': require('../MahjongMacHost/assets/tiles/hd/hd1/b3.png'),
    'b3_side_left': require('../MahjongMacHost/assets/tiles/hd/hd1/b3_side_left.png'),
    'b3_side_right': require('../MahjongMacHost/assets/tiles/hd/hd1/b3_side_right.png'),
    'b4': require('../MahjongMacHost/assets/tiles/hd/hd1/b4.png'),
    'b4_side_left': require('../MahjongMacHost/assets/tiles/hd/hd1/b4_side_left.png'),
    'b4_side_right': require('../MahjongMacHost/assets/tiles/hd/hd1/b4_side_right.png'),
    'b5': require('../MahjongMacHost/assets/tiles/hd/hd1/b5.png'),
    'b5_side_left': require('../MahjongMacHost/assets/tiles/hd/hd1/b5_side_left.png'),
    'b5_side_right': require('../MahjongMacHost/assets/tiles/hd/hd1/b5_side_right.png'),
    'b6': require('../MahjongMacHost/assets/tiles/hd/hd1/b6.png'),
    'b6_side_left': require('../MahjongMacHost/assets/tiles/hd/hd1/b6_side_left.png'),
    'b6_side_right': require('../MahjongMacHost/assets/tiles/hd/hd1/b6_side_right.png'),
    'b7': require('../MahjongMacHost/assets/tiles/hd/hd1/b7.png'),
    'b7_side_left': require('../MahjongMacHost/assets/tiles/hd/hd1/b7_side_left.png'),
    'b7_side_right': require('../MahjongMacHost/assets/tiles/hd/hd1/b7_side_right.png'),
    'b8': require('../MahjongMacHost/assets/tiles/hd/hd1/b8.png'),
    'b8_side_left': require('../MahjongMacHost/assets/tiles/hd/hd1/b8_side_left.png'),
    'b8_side_right': require('../MahjongMacHost/assets/tiles/hd/hd1/b8_side_right.png'),
    'b9': require('../MahjongMacHost/assets/tiles/hd/hd1/b9.png'),
    'b9_side_left': require('../MahjongMacHost/assets/tiles/hd/hd1/b9_side_left.png'),
    'b9_side_right': require('../MahjongMacHost/assets/tiles/hd/hd1/b9_side_right.png'),
  }
};

export function setTileStyle(style: TileStyle) {
  currentTileStyle = style;
}

export function getTileStyle(): TileStyle {
  return currentTileStyle;
}

export function getTileAsset(code: string, side: TileSide = 'upright', style?: TileStyle): any | null {
  const pure = code.includes('@') ? code.split('@')[0] : code;
  const key = side === 'upright' ? pure : `${pure}_${side}`;
  const chosenStyle = style || currentTileStyle;
  return TILE_ASSETS_BY_STYLE[chosenStyle][key] || null;
}
